const dataSoal = [
  [
    'id'=1,
    'soal'='Saya ingin mendatangi satu toko yang disarankan teman. Saya akan:',
    'optA'='mencari toko itu berdasarkan tempat lain di sekitar situ yang sudah saya tahu.',
    'optB'='bertanya pada teman yang tahu arah toko itu.',
    'optC'='menuliskan alamat lengkap dan daftar belokan yang harus saya ingat.',
    'optD'='menggunakan peta yang menunjukkan lokasi toko itu.',
    'valueA'='K',
    'valueB'='A',
    'valueC'='R',
    'valueD'='V'
  ],
  [
    'id'=2,
    'soal'='Suatu situs internet memiliki video mengenai cara membuat suatu grafik khusus. Di situs itu ada orang yang bicara, ada daftar langkah pembuatan video, dan ada beberapa diagram. Saya paling mengerti isi situs itu dengan cara:',
    'optA'='mengamati diagram petunjuknya.',
    'optB'='mendengar suara yang menjelaskan.',
    'optC'='membaca instruksi yang tertulis.',
    'optD'='melihat tindakan orangnya.',
    'valueA'='V',
    'valueB'='A',
    'valueC'='R',
    'valueD'='K'
  ],
  [
    'id'=3,
    'soal'='Saya ingin mengetahui lebih dalam mengenai suatu tur wisata yang saya rencanakan. Saya akan:',
    'optA'='melihat detail kegiatan dan aktivitas yang akan dilakukan.',
    'optB'='melihat petanya dan mengamati lokasi-lokasi turnya.',
    'optC'='membaca perincian jadwal kegiatan tur tersebut.',
    'optD'='bicara dengan pengelola atau peserta lain di tur itu.',
    'valueA'='K',
    'valueB'='V',
    'valueC'='R',
    'valueD'='A'
  ],
  [
    'id'=4,
    'soal'='Dalam memilih karir atau jurusan pendidikan, yang penting bagi saya adalah:',
    'optA'='aplikasi ilmu pada kondisi nyata yang dihadapi.',
    'optB'='berkomunikasi dengan orang dengan berdiskusi.',
    'optC'='pekerjaan yang memakai desain, peta, atau bagan.',
    'optD'='penggunaan kata yang tepat dalam komunikasi tertulis.',
    'valueA'='K',
    'valueB'='A',
    'valueC'='V',
    'valueD'='R'
  ],
  [
    'id'=5,
    'soal'='Saat belajar, saya:',
    'optA'='belajar dengan berdiskusi.',
    'optB'='mencari pola tertentu.',
    'optC'='menggunakan contoh dan penerapan.',
    'optD'='membaca buku dan artikel.',
    'valueA'='A',
    'valueB'='V',
    'valueC'='K',
    'valueD'='R'
  ],
  [
    'id'=6,
    'soal'='Saya ingin menabung lebih banyak dan mempertimbangkan beberapa cara. Saya akan:',
    'optA'='mempertimbangkan contoh dari setiap cara penghematan berdasarkan kondisi keuangan saya.',
    'optB'='membaca brosur tertulis yang menjelaskan cara-cara berhemat secara detail.',
    'optC'='memakai grafik yang menunjukkan variasi pilihan dan jangka waktu yang dibutuhkan.',
    'optD'='bicara dengan ahli keuangan mengenai cara-cara berhemat yang bisa ditempuh.',
    'valueA'='K',
    'valueB'='R',
    'valueC'='V',
    'valueD'='A'
  ],
  [
    'id'=7,
    'soal'='Saya ingin mempelajari suatu jenis permainan kartu yang baru. Saya akan:',
    'optA'='melihat orang lain bermain sebelum saya ikut mencoba.',
    'optB'='mendengar penjelasan orang serta bertanya padanya.',
    'optC'='memakai diagram yang menjelaskan tahap, langkah dan strategi permainannya.',
    'optD'='membaca petunjuk tertulis pada permainan itu.',
    'valueA'='K',
    'valueB'='A',
    'valueC'='V',
    'valueD'='R'
  ],
  [
    'id'=8,
    'soal'='Saya mempunyai masalah jantung. Saya lebih suka dokter yang:',
    'optA'='memberikan bacaan mengenai masalah yang saya hadapi.',
    'optB'='memakai alat peraga jantung untuk menunjukkan masalah yang saya hadapi.',
    'optC'='menguraikan masalah yang saya hadapi.',
    'optD'='menunjukkan diagram mengenai masalah yang saya hadapi.',
    'valueA'='V',
    'valueB'='A',
    'valueC'='R',
    'valueD'='K'
  ],
  [
    'id'=9,
    'soal'='Saya ingin mempelajari suatu program baru di komputer. Saya akan:',
    'optA'='membaca intruksi tertulis pada petunjuknya.',
    'optB'='bicara dengan orang yang paham tentang program itu.',
    'optC'='langsung mencoba dan belajar dari kesalahan.',
    'optD'='mengikuti diagram pada buku petunjuknya.',
    'valueA'='R',
    'valueB'='A',
    'valueC'='K',
    'valueD'='V'
  ],
  [
    'id'=10,
    'soal'='Ketika belajar sesuatu dari internet, saya menyukai:',
    'optA'='video cara melakukan atau membuat sesuatu.',
    'optB'='desain dan fitur visual yang menarik.',
    'optC'='uraian tertulis, daftar dan penjelasan yang menarik.',
    'optD'='situs dengan suara, siaran internet atau wawancara.',
    'valueA'='K',
    'valueB'='V',
    'valueC'='R',
    'valueD'='A'
  ],
  [
    'id'=11,
    'soal'='Saya ingin mempelajari suatu proyek kerja yang baru. Saya akan meminta:',
    'optA'='diagram yang berisi tahap-tahap proyek itu lengkap dengan bagan berisi manfaat dan biayanya.',
    'optB'='laporan tertulis yang menjelaskan bagian utama proyek tersebut.',
    'optC'='kesempatan berdiskusi mengenai proyek tersebut.',
    'optD'='contoh-contoh proyek serupa yang sudah berhasil.',
    'valueA'='V',
    'valueB'='R',
    'valueC'='A',
    'valueD'='K'
  ],
  [
    'id'=12,
    'soal'='Saya ingin belajar cara memotret dengan lebih baik. Saya akan:',
    'optA'='bertanya dan berdiskusi mengenai kamera dan fiturnya.',
    'optB'='membaca instruksi tertulis mengenai cara pemakaian kamera itu.',
    'optC'='melihat diagram yang menunjukkan komponen kamera itu.',
    'optD'='melihat contoh hasil yang baik dan yang jelek dari kamera itu.',
    'valueA'='A',
    'valueB'='R',
    'valueC'='V',
    'valueD'='K'
  ],
  [
    'id'=13,
    'soal'='Saya lebih suka pembicara yang dalam presentasinya menggunakan:',
    'optA'='peragaan, model peraga, atau kesempatan mencoba langsung.',
    'optB'='kesempatan tanya jawab, diskusi kelompok atau pembicara tamu.',
    'optC'='cetakan diktat, buku atau bacaan lain.',
    'optD'='diagram, bagan, peta atau grafik.',
    'valueA'='K',
    'valueB'='A',
    'valueC'='R',
    'valueD'='V'
  ],
  [
    'id'=14,
    'soal'='Saya baru saja menyelesaikan suatu lomba atau suatu ujian dan saya ingin umpan balik orang lain. Saya mengharapkan:',
    'optA'='umpan balik yang berisi contoh-contoh dari yang saya kerjakan.',
    'optB'='umpan balik berupa penjelasan tertulis mengenai hasil pekerjaan saya.',
    'optC'='umpan balik yang disampaikan langsung kepada saya.',
    'optD'='umpan balik dalam bentuk grafik mengenai hasil pekerjaan saya.',
    'valueA'='K',
    'valueB'='R',
    'valueC'='A',
    'valueD'='V'
  ],
  [
    'id'=15,
    'soal'='Saya tertarik dengan suatu rumah atau apartemen. Sebelum berkunjung, saya ingin:',
    'optA'='melihat video rumah atau apartemen itu.',
    'optB'='berdiskusi dengan pemiliknya.',
    'optC'='keterangan tertulis mengenai kamar-kamar dan fiturnya.',
    'optD'='denah ruangan dan peta area sekitarnya.',
    'valueA'='K',
    'valueB'='A',
    'valueC'='R',
    'valueD'='V'
  ],
  [
    'id'=16,
    'soal'='Saya ingin merakit satu set meja kayu yang belum jadi. Saya paling mengerti jika:',
    'optA'='mengikuti diagram instruksi yang dilampirkan.',
    'optB'='mendengar saran dari orang yang pernah merakitnya.',
    'optC'='membaca penjelasan tertulis yang dilampirkan.',
    'optD'='menonton video orang merakit meja yang serupa.',
    'valueA'='V',
    'valueB'='A',
    'valueC'='R',
    'valueD'='K'
  ]
]